<!DOCTYPE html>
<html>
<head>
    <title>List of all students</title>
    <style>
       table{
        border-collapse: collapse;
       }
        
        th {
            background-color: #000;
            color: #fff;
            border: 1px solid #000;
            text-align: left;
            font-size: 12px;
            padding: 4px;
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: 2px;
            text-align: center;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        
        td {
            border: 1px solid #000;
            text-align: center;
            padding: 2px;
            /* font-size: x-small; */
        }
        
        .divTableCell,
        .divTableHead {
            padding: 0px !important;
            border: 0px !important;
            font-size: x-small;

        }
    </style>
</head>
<body style='display:flex; flex-direction:column; justify-content:space-between;'>
    <div>
        <div style="text-align: center;">
            <h2>Strathmore University International Students Affairs</h2>
            <h3>Office of the Dean of Students</h3>    
        </div>
        <div style="text-align: center;">
            <i class="fas fa-table mr-1" style="text-decoration:underline"></i><u>
                List of all Registered Students.</u>
        </div><br/>    
        <div class="row">             
            <div class="table table-bordered"  >
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Student</th>
                        <th>email</th>
                        <th>Phone</th>
                        <th>Buddy</th>
                        <th>email</th>
                        <th>Phone</th>
                    </tr>
                </thead>
                @foreach($allocations as $allocation)
                    <tr>
                        <td>{{$allocation['surname'].' '.$allocation['other_names']}}</td>
                        <td>{{$allocation['email']}}</td>
                        <td>{{$allocation['phone_number']}}</td>
                        <td>{{$allocation['bd_srnm'].' '.$allocation['bd_onm']}}</td>
                        <td>{{$allocation['bd_eml']}}</td>
                        <td>{{$allocation['bd_phn']}}</td>
                    </tr>
                @endforeach
                    </tbody>
                </table>
    
                
            </div>
        </div>

    </div>
    <div style='border-top: 1px solid rgba(110,110,110,.75); '>
        <small class="mb-0"><strong>Report Generated on</strong>: <?php echo date('d.m.Y'); ?></small><br>
        <small><strong>Time Generated </strong>: <?php date_default_timezone_set("Africa/Nairobi"); echo date("h:i:sa");?></small><br>
        <small><strong>Generated By </strong>: {{ Auth::user()->other_names}}</small>
    </div>
</body>
</html>