<!DOCTYPE html>
<html>
<head>
    <title>List of all students</title>
    <style>
       table{
        /* border-collapse: collapse; */
       }
        
        th {
            background-color: #000;
            color: #fff;
            border: 1px solid #000;
            text-align: left;
            /* font-size: 12px; */
            padding: 2px;
            text-transform: capitalize;
            font-weight: bold;
            letter-spacing: 2px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        
        td {
            border-color: #959594;
            border-style: solid;
            border-width: 1px;
            font-size: x-small;
            /* font-size: x-small; */
        }
        
        .divTableCell,
        .divTableHead {
            padding: 0px !important;
            border: 0px !important;
            font-size: x-small;

        }
    </style>
</head>
<body style='display:flex; flex-direction:column; justify-content:space-between;'>
    <div>
        <div style="text-align: center; display:flex; ">
            <img src="data:image/png;base64,{{base64_encode(file_get_contents(public_path('asset/img/logo.png')))}}" style="width:220px; height:150px;">
            <h2>Strathmore University International Students Affairs</h2>
        </div>
        <div style="text-align: center;">
            <i class="fas fa-table mr-1" style="text-decoration:underline"></i><u>
                List of all Registered Students.</u>
        </div><br/>    
        <div class="row">             
            <div class="table table-bordered"  >
                <table id="dataTable" width="100%" >
                    <thead>
                        <tr> 
                            <th>No</th>
                            <th>SU Id</th>
                            <th> Surname Name</th>
                            <th> Other Names</th>
                            <th> Su Email</th>
                            <th> Course</th>
                            <th> Nationality<th>               
                        </tr>
                    </thead>
                    <tbody>
                    @php $count=1; @endphp
                    @foreach($users as $user)
                        @if(array_key_exists('role',$user))
                            @if($user['role'] === 'student')
                            <tr>
                                <td>{{$count}}</td>
                                <td>{{$user['user_id']}}</td>
                                <td>{{$user['surname']}}</td>
                                <td>{{$user['other_names']}}</td>
                                <td>{{$user['email']}}</td>
                                @if(array_key_exists('course',$user))
                                    <td>{{$user['course']}}</td>
                                @endif
                                @if(array_key_exists('nationality',$user))
                                    <td>{{$user['nationality']}}</td>
                                @endif

                            </tr>
                            @php $count= $count+1; @endphp
                            @endif
                        @endif
                    @endforeach
                        </tbody>
                </table>
    
                
            </div>
        </div>

    </div>
    <div style='border-top: 1px solid rgba(110,110,110,.75); '>
        <small class="mb-0"><strong>Report Generated on</strong>: <?php echo date('d.m.Y'); ?></small><br>
        <small><strong>Time Generated </strong>: <?php date_default_timezone_set("Africa/Nairobi"); echo date("h:i:sa");?></small><br>
        <small><strong>Generated By </strong>: {{ Auth::user()->other_names}}</small>
    </div>
</body>
</html>