
<!DOCTYPE html>
<html>
<head>
    <title>List of Buddy Allocations</title>
</head>
<body>
    <div style="text-align: center;">
    </div>
    <div style="text-align: center;">
    <h2>Strathmore University International Students Affairs</h2>
    <h3>Office of the Dean of Students</h3>    
    </div>
    <div style="text-align: center;">
    <i class="fas fa-table mr-1" style="text:underline"></i><u>
            List of all Buddy Allocations.</u>
    </div><br/>    
        <div class="row">             
        <div class="table table-bordered"  >
         <table id="datatable" width="100%" cellspacing="0" class="table table-bordered">                   
                <thead>
                     <tr>  
                        <th align="left">
                            No.
                        </th>                    
                        <th align="left">
                            Buddy Names
                        </th>
                        <th align="left">
                            Buddy suid
                        </th>
                        <th align="left">
                            Student Name
                        </th>
                        <th align="left">
                            Student suid
                        </th>
                        <th align="left">
                            Email
                        </th>
                        <th align="left">
                            Course
                        </th>
                        
                    </tr>
                </thead>
               
                 <tbody>
                    @php
                    $counter=1;
                    @endphp
                    @foreach($data as $data)  
                   
                    <tr class="active">
                        <td align="left">{{$counter}}</td>
                        <td align="left">{{$data['Buddy_otherNAMES']}}</td>
                        <td align="center">{{$data['Buddy_suID']}}</td>
                        <td align="left">{{$data['NewSTD_otherNAMES']}}</td>
                        <td align="left">{{$data['NewSTD_suID']}}</td>
                        <td align="left">{{$data['NewSTD_email']}}</td>
                        <td align="left">{{$data['NewSTD_course']}}</td>
                    </tr>
                    @php
                    $counter++;
                    @endphp  
                @endforeach
                    <tr>
                    <td colspan="8">
                    <p class="mb-0"><strong>Report Generated on</strong>: <?php echo date('d.m.Y'); ?></p>
                    <p><strong>Time Generated </strong>: <?php date_default_timezone_set("Africa/Nairobi"); echo date("h:i:sa");?></p>
                    <p><strong>Generated By </strong>: {{ Auth::user()->otherNAMES}}</p>

                    </td>
                    </tr>
                    <tr>
                    <td align="left" style="visibility:hidden;">{{$data['id']}}</td>
                    </tr>
                </tbody>
            </table>
            </div>
</div>
</body>

</html>
