<!DOCTYPE html>
<html>
<head>
    <title>List of all students</title>
    <style>
       table{
        border-collapse: collapse;
       }
        
        th {
            background-color: #000;
            color: #fff;
            border: 1px solid #000;
            text-align: left;
            font-size: 12px;
            padding: 4px;
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: 2px;
            text-align: center;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        
        td {
            border: 1px solid #000;
            text-align: center;
            padding: 2px;
            /* font-size: x-small; */
        }
        
        .divTableCell,
        .divTableHead {
            padding: 0px !important;
            border: 0px !important;
            font-size: x-small;

        }
    </style>
</head>
<body style='display:flex; flex-direction:column; justify-content:space-between;'>
    <div>
        <div class='d-flex flex-column justify-content-center' style="text-align: center;">
            <!-- <img src="logo.png" style="width:300px; height:200px;"> -->
            <img src="data:image/png;base64,{{base64_encode(file_get_contents($img))}}" style="width:300px; height:200px;">
            <!-- <p>{{$img}}</p> -->
            <h2>Strathmore University International Students Affairs</h2>
            <h3>Office of the Dean of Students</h3>    
        </div>
        <div style="text-align: center;">
            <i class="fas fa-table mr-1" style="text-decoration:underline"></i><u>
                List of all Registered Buddies.</u>
        </div><br/>    
        <div class="row">             
            <div class="table table-bordered"  >
                <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                    <thead class="thead-dark">
                        <tr>
                            <th>id</th>
                            <th>Name</th>
                            <th>email</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(sizeOf($buddies) === 0)
                        <tr>
                            <td colspan="4">No Buddy found</td>
                        </tr>
                        @endif
                        @foreach($buddies as $buddy)
                            <tr>
                                <td>{{$buddy->id}}</td>
                                <td>{{$buddy->surname.' '.$buddy->other_names}}</td>
                                <td>{{$buddy->email}}</td>
                            </a>  
                            </tr>
                        @endforeach
                        </tbody>
                </table>
    
                
            </div>
        </div>

    </div>
    <div style='border-top: 1px solid rgba(110,110,110,.75); '>
        <small class="mb-0"><strong>Report Generated on</strong>: <?php echo date('d.m.Y'); ?></small><br>
        <small><strong>Time Generated </strong>: <?php date_default_timezone_set("Africa/Nairobi"); echo date("h:i:sa");?></small><br>
        <small><strong>Generated By </strong>: {{ Auth::user()->other_names}}</small>
    </div>
</body>
</html>