
<!DOCTYPE html>
<html>
<head>
    <title>List of Buddy Allocations</title>
    <style>
       
        
        th {
            background-color: #f7f7f7;
            border-color: #959594;
            border-style: solid;
            border-width: 1px;
            text-align: left;
                        font-size: x-small;

        }
        
        .bordered td {
            border-color: #959594;
            border-style: solid;
            border-width: 1px;
                        font-size: x-small;

        }
        
        table {
            border-collapse: collapse
                        font-size: x-small;

        }
        
        .divTableCell,
        .divTableHead {
            padding: 0px !important;
            border: 0px !important;
            font-size: x-small;

        }
    </style>
</head>
<body>
   
    <div class='d-flex flex-column justify-content-center' style="text-align: center;">
        <img src="/asset/img/logo.png'" style="width:300px; height:200px;">
        <h2>Strathmore University International Students Affairs</h2>
        <h3>Office of the Dean of Students</h3>    
    </div>
    <div style="text-align: center;">
    <i class="fas fa-table mr-1" style="text:underline"></i><u>
            List of all Registered Buddies.</u>
    </div><br/>    
        <div class="row">             
        <div class="table table-bordered"  >
         <table id="datatable" width="100%" cellspacing="0" class="table table-bordered">                   
                <thead>
                     <tr>  
                       <th align="left">
                            No.
                        </th>                    
                       
                        <th align="left">
                            Surname
                        </th>
                        <th align="left">
                            Othernames
                        </th>
                        <th align="left">
                            Email
                        </th>
                        <th align="left">
                            Course
                        </th>
                        <th align="left">
                            Phone
                        </th>
                        <th align="left">
                            suID
                        </th>
                        
                    </tr>
                </thead>
               
                 <tbody>
                    @php
                    $counter=1;
                    @endphp
                    @foreach($data as $itm)  
                   
                    <tr class="active">
                        <td align="left">{{$counter}}</td>
                        <td align="left">{{$itm->id}}</td>
                        <td align="left">{{$itm->surname}}</td>
                        <td align="left">{{$itm->other_names}}</td>
                        <td align="left">{{$itm->email}}</td>
                    </tr>
                    @php
                    $counter++;
                    @endphp 
                    @endforeach
                    <tr>
                    <td colspan="8">
                    <p class="mb-0"><strong>Report Generated on</strong>: <?php echo date('d.m.Y'); ?></p>
                    <p><strong>Time Generated </strong>: <?php date_default_timezone_set("Africa/Nairobi"); echo date("h:i:sa");?></p>
                    <p><strong>Generated By </strong>: {{ Auth::user()->other_names}}</p>

                    </td>
                    </tr>
                    <tr>
                    <td align="left" style="visibility:hidden;">{{$itm->id}}</td>
                    </tr>
                </tbody>
            </table>
            </div>
</div>
</body>

</html>
