
<!DOCTYPE html>
<html>
<head>
    <title>List Of International Students</title>
    <style>
       
        
        th {
            background-color: #f7f7f7;
            border-color: #959594;
            border-style: solid;
            border-width: 1px;
            text-align: left;
                        font-size: x-small;

        }
       
        .bordered td {
            border-color: #959594;
            border-style: solid;
            border-width: 1px;
                        font-size: x-small;

        }
        
        table {
            border-collapse: collapse
                        font-size: x-small;

        }
        
        .divTableCell,
        .divTableHead {
            padding: 0px !important;
            border: 0px !important;
            font-size: x-small;

        }
    </style>
</head>
<body>   
    <div style="text-align: center;">
    <h2>Strathmore University International Students Office</h2>
    <h3>Office of the Dean of Students</h3>    
    </div>
    <div style="text-align: center;">
    <i class="fas fa-table mr-1" style="text:underline"></i><u>
            List of all Registered International Students.</u>
    </div><br/>    
       
        <div class="divTable">
        <div class="divTableBody">
            <div class="divTableRow">

                <div class="divTableCell">

                <table id="ListTable" class="bordered width-100pc">                   
                <thead>
                     <tr> 
                         <th align="left">
                           No
                        </th>
                        <th align="left">
                            First Name
                        </th>
                        <th align="left">
                            Last Name
                        </th>
                        <th align="left">
                            Su Email
                        </th>
                        <th align="left">
                            Course
                        </th>
                        <th align="left">
                            Nationality
                        </th>                        
                    </tr>
                </thead>
                <tbody>
                    @php
                    $counter=1;
                    @endphp
                    @foreach($students as $student)  
                   
                    <tr class="active"> 
                        <td align="left">{{$counter}}</td>
                        <td align="left">{{$student['firstNAME']}}</td>
                        <td align="left">{{$student['lastNAME']}}</td>
                        <td align="left">{{$student['suEMAIL']}}</td>
                        <td align="left">{{$student['Course']}}</td>
                        <td align="left">{{$student['Nationality']}}</td>
                    </tr>
                    @php
                    $counter++;
                    @endphp
                @endforeach
                    
                    <tr>
                    <td align="left" style="visibility:hidden;">{{$student['id']}}</td>
                    </tr>
                </tbody>
            </table>
            <Div id="credit">
            <p class="mb-0"><strong>List Generated on</strong>: <?php echo date('d.m.Y'); ?></p>
                    <p><strong>Time Generated </strong>: <?php date_default_timezone_set("Africa/Nairobi"); echo date("h:i:sa");?></p>
                    <p><strong>Generated By </strong>: {{ Auth::user()->otherNAMES}}</p>

                </div>
</div>
</div>
</div>
</div>
    
</body>
</html>
